version: '3.8'

services:
  db:
    image: postgres:latest
    restart: unless-stopped
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - ./data/db:/var/lib/postgresql/data
  web:
    build: .
    command: bash -c "python manage.py migrate --noinput && python manage.py runserver 0.0.0.0:8010"
    volumes:
      - .:/code
    ports:
      - "8010:8010"
    depends_on:
      - db
    env_file:
      - .env