# Generated by Django 3.2 on 2022-09-14 05:47

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TypeNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('color', models.CharField(max_length=7, unique=True, validators=[django.core.validators.RegexValidator(message='The color of type in the format #XXXXXX (X - number from 0 to 9 or capital letters from A to Z)', regex='#[A-Z\\d]+')])),
            ],
        ),
        migrations.CreateModel(
            name='TheNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('short_description', models.TextField(max_length=50)),
                ('long_description', models.TextField(max_length=1000)),
                ('type_of_news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news', to='core.typenews')),
            ],
            options={
                'verbose_name': 'News',
                'verbose_name_plural': 'News',
            },
        ),
    ]
